version: "3.9"

services:
  nexusd:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["-config", "/etc/nexus/nexus.toml"]
    volumes:
      - ./examples/docker-compose/nexus.compose.toml:/etc/nexus/nexus.toml:ro
      - nexus-run:/run/nexus
    restart: unless-stopped

  docker-service:
    build:
      context: .
      dockerfile: ./examples/docker-service/Dockerfile
    environment:
      - NEXUS_SERVICE_SOCKET=/run/nexus/examples/docker-service.sock
    volumes:
      - nexus-run:/run/nexus
    depends_on:
      - nexusd

volumes:
  nexus-run:
